### PR TITLE
fix: remove trailing slash from serverUrl input

### LINKED ISSUE #1146: trim trailing `/` when pasting severUrl into sasjs cli prompt
When adding `serverUrl` in both `sasjs add` and `sasjs auth` we should strip any trailing slashes when saving to the sasjsconfig.json file.

We should also save to the sasjsconfig file immediately, so that it is saved if the user aborts the prompts.

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1146 

## Intent

*  remove leading slash from serverUrl input

## Implementation

* `serverUrl.replace(/\/$/, '')`

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/add/internal/input.ts [hunk 1]
```diff
@@ -89,7 +89,7 @@ export async function getAndValidateServerUrl(target?: TargetJson) {
     target?.serverUrl
   )
 
-  return serverUrl
+  return serverUrl.replace(/\/$/, '')
```
Comment (medjedovicm) [inline src/commands/add/internal/input.ts:92]: In the title, it says the leading slash should be removed, but `$` in regex will match the last character (trailing slash)

Comment (allanbowe) [reply src/commands/add/internal/input.ts:92]: aah, that's a bad title.  It should be trailing slash.  Good spot!

**Review by allanbowe — APPROVED** [review]
