### PR TITLE
fix(create): fetching template info without curl

### LINKED ISSUE #321: certificate issue in portable git bash on windows
Problem:

The `sasjs create someProject -t jobs` command fails with an exception

Cause:

When running portable git bash on a locked down windows machine the underlying `curl` command fails with a certificate error:

image

Interestingly the same command works fine in the `cmd` shell.  

Action:
Rather than throw an exception we should handle this case and present the result back to the user.

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #321 

## Intent

Remove `curl`'s only existence from code, it requires certificates to be configured. Some users have issue on windows with portable git-bash

## Implementation

removed `curl` (calling github api), replaced with `git ls-remote`

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.
image

To test:
checkout branch `issue321` and `npm start`

### CODE REVIEW

File: src/utils/utils.js [hunk 1]
```diff
@@ -37,19 +37,24 @@ export async function createMinimalApp(folderPath) {
 }
 
 export async function createTemplateApp(folderPath, template) {
-  const {
-    stdout
-  } = shelljs.exec(
-    `curl https://api.github.com/repos/sasjs/template_${template}`,
-    { silent: true }
+  const { stdout, stderr, code } = shelljs.exec(
+    `git ls-remote git@github.com:sasjs/template_${template}`,
```
Comment (allanbowe) [inline src/utils/utils.js:41]: Will this approach (git@github) still work even if the user does not have an ssh key?

Comment (saadjutt01) [reply src/utils/utils.js:41]: yes, because our template repositories are public. No ssh key is required.

**Review by allanbowe — APPROVED** [review]

**Review by allanbowe — DISMISSED** [review]

File: src/utils/utils.js [hunk 2]
```diff
@@ -37,19 +37,20 @@ export async function createMinimalApp(folderPath) {
 }
 
 export async function createTemplateApp(folderPath, template) {
-  const {
-    stdout
-  } = shelljs.exec(
-    `curl https://api.github.com/repos/sasjs/template_${template}`,
-    { silent: true }
+  const { stdout, stderr, code } = shelljs.exec(
+    `git ls-remote https://username:password@github.com/sasjs/template_${template}.git`,
```
Comment (allanbowe) [inline src/utils/utils.js:41]: so the dummy username:password prevents the authentication prompt when the user provides the wrong template name?

Nice!

**Review by allanbowe — APPROVED** [review]
