### PR TITLE
fix: sasjs fs sync with no arguments should deploy per the sasjsconfig

### LINKED ISSUE #1282: `sasjs fs sync` with no arguments should deploy per the sasjsconfig
If `sasjs fs sync` is executed without arguments then we should check the default (or -t specified) target in the project (and then the user-level) config file for the `syncDirectories` array.

If not found, we should say:

> No syncDirectories found

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1282

## Intent

* If sasjs fs sync is executed without arguments then we should check the default (or -t specified) target in the project (and then the user-level) config file for the syncDirectories array.

## Implementation

* made localFolder and remoteFolder optional and replaced with just local (alias `l`) and remote (alias `r`)
* added a config utility to get all sync directories from target and root of sasjs config
* loop on syncDirectories array returned from `getSyncDirectories`

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/fs/fsCommand.ts [hunk 1]
```diff
@@ -24,11 +25,13 @@ enum FsSubCommand {
 
 const syntax = 'fs <subCommand> [options]'
 const usage = 'Usage: sasjs fs <subCommand> [options]'
-// TODO: update
 const description = 'Handles operations around file system synchronisation'
+const parseOptions = {
+  output: { type: 'string', alias: 'o' }
```
Comment (YuryShkoda) [inline src/commands/fs/fsCommand.ts:30]: what does `alias: 'o'` mean?

File: src/commands/fs/fsCommand.ts [hunk 2]
```diff
@@ -39,20 +42,32 @@ const compileCommandExamples: CommandExample[] = [
...
+      'sasjs fs sync -l <path/of/folder> -r <path/of/remote/folder> -t <target-name>',
+    description: ''
   }
 ]
 
-const parseOptions = {
-  output: { type: 'string', alias: 'o' }
+const syncCommandParseOptions = {
+  ...parseOptions,
+  local: { type: 'string', alias: 'l' },
```
Comment (YuryShkoda) [inline src/commands/fs/fsCommand.ts:69]: we should create an enum for aliases

**Review by YuryShkoda — DISMISSED** [review]

**Review by allanbowe — APPROVED** [review]
