### PR TITLE
fix: should not authenticate against sasjs server running in desktop mode

### LINKED ISSUE #1216: `sasjs auth` and `sasjs add` should have a check to avoid client authentication in desktop mode

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1216

## Intent

* there's no need to authenticate against the target containing `serverType == SASjs` and the server is running in desktop mode.

## Implementation

* Added a utility function that calls the server's info api endpoint and checks if the server is running in server mode or not.

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/utils/utils.ts [hunk 1]
```diff
@@ -489,3 +490,14 @@ export const getNodeModulePath = async (module: string): Promise<string> => {
   // Return default value
   return ''
 }
+
+export const isServerRunningInServerMode = async (target: Target) => {
+  try {
+    const res = await axios.get(`${target.serverUrl}/SASjsApi/info`)
+    if (res.data.mode === 'server') return true
```
Comment (medjedovicm) [inline src/utils/utils.ts:497]: Could be written shorter like this:

```
return res.data.mode === 'server'
```

**Review by medjedovicm — APPROVED** [review]

**Comment by allanbowe** [comment]
Before we merge this, given the additional dependency, it would be good to know two things:

1.  Will `npm i -g @sasjs/cli` continue to install without errors or warnings
2.  What is the impact on the bundle size, and hence the time to download the CLI?

**Review by allanbowe — CHANGES_REQUESTED** [review]
Before we merge this, given the additional dependency, it would be good to know two things:

1.Will npm i -g @sasjs/cli continue to install without errors or warnings
2. What is the impact on the bundle size, and hence the time to download the CLI?

File: package.json [hunk 2]
```diff
@@ -52,6 +52,7 @@
     "@sasjs/lint": "1.11.2",
     "@sasjs/utils": "2.45.0",
     "adm-zip": "0.5.9",
+    "axios": "0.27.2",
```
Comment (YuryShkoda) [inline package.json:55]: You don't need to add `axios` as a dependency because it is already there (brought by `@sasjs/adapter`)

File: src/utils/utils.ts [hunk 3]
```diff
@@ -489,3 +490,14 @@ export const getNodeModulePath = async (module: string): Promise<string> => {
   // Return default value
   return ''
 }
+
+export const isServerRunningInServerMode = async (target: Target) => {
```
Comment (YuryShkoda) [inline src/utils/utils.ts:494]: I would call it `isSasJsServerInServerMode`

File: package-lock.json [hunk 4]
```diff
@@ -2093,6 +2093,14 @@
         "valid-url": "1.0.9"
       }
     },
+    "node_modules/@sasjs/adapter/node_modules/axios": {
```
Comment (YuryShkoda) [inline package-lock.json:2096]: @sabhas , please roll back changes to `package-lock.json`

**Comment by sabhas** [comment]
> 

we are no longer adding any additional dependency in this PR

**Review by YuryShkoda — APPROVED** [review]

**Comment by sabhas** [comment]
> Before we merge this, given the additional dependency, it would be good to know two things:
> 
> 1.Will npm i -g @sasjs/cli continue to install without errors or warnings 2. What is the impact on the bundle size, and hence the time to download the CLI?


we are no longer adding any additional dependency in this PR

**Review by allanbowe — APPROVED** [review]
