### PR TITLE
fix: use process variable instead of hard coded sasjsbuild

### LINKED ISSUE #1327: `sasjsBuildFolder` not being applied in `sasjs c`
To reproduce:

```
sasjs create demo -t jobs
cd demo
vi sasjs/sasjsconfig.json  
# Add this line:    "sasjsBuildFolder":"test",
sasjs c
ls
```

Expected - the `sasjsbuild` folder should not be listed.

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1327

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/deploy/internal/executeNonSasScript.ts [hunk 1]
```diff
@@ -8,9 +8,10 @@ import { isShellScript, isPowerShellScript } from '../../../utils/file'
 export async function executeNonSasScript(scriptPath: string) {
   const fileExtension = path.extname(scriptPath)
 
+  const { buildDestinationResultsLogsFolder } = process.sasjsConstants
```
Comment (allanbowe) [inline src/commands/deploy/internal/executeNonSasScript.ts:11]: would be good to get a comment here explaining what `buildDestinationResultsLogsFolder` is.  The variable name contains both "build" and "results" so it might be ambiguous as to whether it's `sasjsbuild` or `sasjsresults`

Comment (sabhas) [reply src/commands/deploy/internal/executeNonSasScript.ts:11]: good point!
For now, we can add a comment explaining this point but we should rename these constants in the future.

**Review by YuryShkoda — APPROVED** [review]
