### PR TITLE
fix(job flags): --log, --output and new --status

### LINKED ISSUE #250: update syntax for 'sasjs job' command
Flag `--log` has to be changed to `--logFile` with aliases `--log` and `-l`

Flag `--output` should be changed so that it outputs to a FILE (not folder)

Flag `--status` should be added, to contain the status (eg error, success) of the job.  It should point to a FILE, and the file will contain the value of the status.  The status should also be printed to the log (success green, error red) if `--wait` is in effect.

To clarify - the final command might look like this:

```
sasjs job execute [somejob] --log /folder/file.log --output /folder/output.json --status /folder/file.txt
```

Also - we need to make sure that logs are generated when a job errors.  The tests should include failing jobs.

A job can be made to fail by including the following sas code:  `%abort;`

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #250 

## Intent

To update `--log` flag, `--output` flag's behavior and add new `--status` flag
++ handle absolute paths for `output`, `logfile` and `status`
++ handle `~` for win paths
++ use default context if not specified

## Implementation

Updated command utility:
- for `--log` flag updated to `--logFile` and alias are working i.e. `--log` and `-l`
- to have another flag `--status`
Update job execute code to have `status: success` in output file in case of `wait` and print on screen.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
tested with unreleased adapter 
image
- [ ] All CI checks are green.
- [x] JSDoc comments have been added or updated.

## Steps to test
- checkout branch `issue250`
- `npm install`
- `npm link`
- verify with `npm -v` it should give you the path of local repository of sasjs-cli
_You are using a linked version of SASjs CLI running from sources at 1.0.0   {PATH}_

### CODE REVIEW

File: src/commands/job/execute.js [hunk 1]
```diff
@@ -47,14 +52,17 @@ export async function execute(
     )
     .catch((err) => {
       result = err
-
+      // need to fix this error return, it's not printing `err` on console
```
Comment (krishna-acondy) [inline src/commands/job/execute.js:55]: Should we not just throw an error here? It'll be caught by the layer above and be displayed in the console.

File: src/commands/job/execute.js [hunk 2]
```diff
@@ -156,3 +165,27 @@ export async function execute(
...
+    submittedJob && submittedJob.state ? submittedJob.state : 'Not Available'
+  const status =
+    adapterStatus === 'Not Available'
+      ? `Job Status: ${adapterStatus}\n\nDetails: ${result}`
+      : `Job Status: ${adapterStatus}`
+
+  if (adapterStatus === 'completed') displayResult(null, null, status)
+  else displayResult(result, status, null)
+
+  if (typeof statusOfJob === 'string') {
```
Comment (krishna-acondy) [inline src/commands/job/execute.js:180]: The `JSDoc` comment above indicates that `statusOfJob` is a boolean.
Are we 'reusing' that to pass in a path? I also feel like the variable could be named differently to better reflect its intent.

Comment (saadjutt01) [reply src/commands/job/execute.js:180]: JSDoc needs to be updated, since approach is changed
Yes it's not boolean flag anymore.

File: src/commands/job/execute.js (hunk 1 above)
Comment (saadjutt01) [reply src/commands/job/execute.js]: updated

File: src/commands/job/execute.js [hunk 3]
```diff
@@ -15,6 +15,7 @@ import path from 'path'
  * @param {boolean} output - flag indicating if CLI should print out job output. If string was provided, it will be treated as file path to store output.
  * @param {boolean | string} output - flag indicating if CLI should print out job output. If string was provided, it will be treated as file path to store output. If filepath wasn't provided, output.json file will be created in current folder.
  * @param {boolean | string} log - flag indicating if CLI should fetch and save log to the local folder. If filepath wasn't provided, {job}.log file will be created in current folder.
```
Comment (allanbowe) [inline src/commands/job/execute.js:17]: This description should be updated (and maybe the parameter name)

For executing jobs, we always provide a `logFile` (path to a file), never a folder

File: test/commands/job.spec.js [hunk 4]
```diff
@@ -98,6 +98,47 @@ describe('sasjs job', () => {
...
+        await expect(folderExists(folderPath)).resolves.toEqual(true)
+        await expect(fileExists(filePath)).resolves.toEqual(true)
+      },
+      60 * 1000
+    )
+
+    it(
+      'should submit a job and create a file with job output, log and auto-wait',
+      async () => {
+        const command = `job execute /Public/app/cli-tests/testJob -t ${targetName} -o testOutput -l testLog`
```
Comment (allanbowe) [inline test/commands/job.spec.js:120]: `-l testLog/some.file` should be the paramter

File: test/utils/command.spec.js [hunk 5]
```diff
@@ -486,16 +486,23 @@ describe('parseCommandLine', () => {
 
     test('short syntax', () => {
       const commandLine =
-        'job execute /Public/job -t targetName -w -o ./output.json -l ./log.json'
+        'job execute /Public/job -t targetName -w -o ./output.json -l ./log.json -s ./status.txt'
```
Comment (allanbowe) [inline test/utils/command.spec.js:489]: the log should not arrive in JSON format (not sure if that fix is merged yet though)

**Review by allanbowe — CHANGES_REQUESTED** [review]

**Comment by allanbowe** [comment]
So the `/state` endpoint always returns successful, even when the job errors or has warnings.

We should query the `stateDetails` instead, in order to find out the state of the job.  

https://developer.sas.com/apis/rest/v3.5/Compute/#job-39-s-statedetails-registry

**Review by allanbowe — APPROVED** [review]

**Review by krishna-acondy — APPROVED** [review]
