### PR TITLE
fix: save log when sasjs request is successful and save empty json fi…

### LINKED ISSUE #1156: save log when sasjs request is successful and save empty json file if no output

### PR DESCRIPTION
**Pull request by sabhas**
…le if no output

## Issue

closes #1156 

## Intent

* Always save log file even when request finishes successfully
* if `res.result` is empty then save empty output file

## Implementation

What code changes have been made to achieve the intent.

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/request/request.ts [hunk 1]
```diff
@@ -107,15 +107,17 @@ export async function runSasJob(
...
+      await writeOutput(outputPathParam, output, isLocal)
+      await saveLogFile(sasjs, sasJobLocation, logFile, jobPath)
       result = true
     })
     .catch(async (err: any) => {
       if (err && err.errorCode === 404) {
         displaySasjsRunnerError(configJson.username)
       } else {
-        displayError(err, 'An error occurred while executing the request.')
+        displayError('', 'An error occurred while executing the request.')
```
Comment (allanbowe) [inline src/commands/request/request.ts:120]: what is the reason for not displaying `err` ?

Comment (allanbowe) [reply src/commands/request/request.ts:120]: If there is an `err.errorCode` that would be quite relevant.  The problem is that SAS can fail for many reasons, so without those details, it becomes impossible for the end user to debug

**Review by medjedovicm — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
