### PR TITLE
fix(*): fixed linkes to files

### LINKED ISSUE #349: Improve 'job execute' command validation
`sasjs job execute jobs/job -l logs/some .log -t targetName` in such case the job will not be submitted for execution.
A warning should be printed.

### PR DESCRIPTION
**Pull request by YuryShkoda**
## Issue

closes #349

## Intent

1. Provide absolute file paths to the `logs` and `csv` files.
2. Save `csv` file to the default location if the location was not provided. 
3. Format timestamp in log file name.
4. Fix trailing dot in CLI output.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

### CODE REVIEW

File: src/commands/flow/execute.ts [hunk 1]
```diff
@@ -70,16 +80,26 @@ export async function execute(
...
     })
 
+    const defaultCsvFileName = 'flowResults.csv'
+
     if (csvFile) {
-      if (!isCsvFile(csvFile)) {
-        return reject(
-          `Please provide csv file location (--csvFile).\n${examples.command}`
-        )
+      if (csvFile.includes('.')) {
```
Comment (saadjutt01) [inline src/commands/flow/execute.ts:86]: isn't should starts with `.`

**Review by saadjutt01 — APPROVED** [review]
