### PR TITLE
fix(doc): support case-insensitve filename for 'doxyfile' + escaping double qoutes & escape characters

### LINKED ISSUE #578: sasjs doc fails when @brief attribute contains double quotes
To reproduce, open this link:  https://gitpod.io/#github.com/sasjs/template_jobs

Then update the job header as per this screenshot and run `sasjs doc`

image

embedded quotes need to be escaped in the DOT file before they can be rendered.

It would also be nice if the DOT file would be saved in the sasjs doc output folder before it is rendered.  This would help with debugging, as well as diagram re-use.

- [ ] sasjs doc supports quotes in the BRIEF when data lineage is enabled
- [ ] DOT output is saved in doc output folder
- [ ] at least one new test case is created

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #578
Support case-insensitive filename for doxygen configuration, currently its `Doxyfile`

## Intent

`sasjs doc`  should not fail when @brief attribute contains double quotes
doxygen configuration filename should be case-insensitive

## Implementation

Updated `createDotFiles.ts` 
- Added try catch for future unknown errors
- Added file creation logger messages

Updated `getDotFileContent.ts `
- embedded quotes escaped before writing to DOT file

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

### CODE REVIEW

**Review by krishna-acondy — APPROVED** [review]

File: src/commands/docs/internal/getDotFileContent.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export async function getDotFileContent(
 
       fileNodes.set(fileName, {
         edges: fileOutputs,
-        label: `${fileName} | ${fileBrief}`
+        label: `${fileName} | ${fileBrief}`.replace(/"/g, '\\"')
```
Comment (allanbowe) [inline src/commands/docs/internal/getDotFileContent.ts:45]: maybe we could also escape backslash here also?

Comment (saadjutt01) [reply src/commands/docs/internal/getDotFileContent.ts]: added

**Review by allanbowe — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
