### PR TITLE
fix: using debug true on adapter instances, stringifying the error logs

### LINKED ISSUE #220: sasjs run issues
1) the log is not being returned (just the json object).  We should extract the log, be sure to set limit=10000 or some high number, and convert the JSON to a text file.

2) the command line does not wait for the code to finish running.  Instead it returns the folowing:

image

Expectation - log is output in plain text format (same as for sasjs job).  The command line waits for the result by default.

### PR DESCRIPTION
**Pull request by medjedovicm**
## Issue

Closes #220 

## Intent

Using debug true in adapter instances and stringifying the logs.
Fixing the terminal not waiting for job to finish.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
image
- [x] All CI checks are green.
- [x] JSDoc comments have been added or updated.

## Screenshots
Screenshot from 2020-11-29 14-08-43
Screenshot from 2020-11-29 14-08-57

### CODE REVIEW

**Comment by medjedovicm** [comment]
Couldn't reproduce `not waiting job to finish` point. On Windows and Git Bash

**Review by allanbowe — DISMISSED** [review]

File: src/commands/run.js [hunk 1]
```diff
@@ -65,13 +67,21 @@ async function executeOnSasViya(filePath, buildTarget, linesToExecute) {
...
+      contextName,
+      accessToken,
+      executionSession.id
+    )
+    .catch(async (err) => {
+      let log = err.log
+
+      await createOutputFile(log)
+
+      throw new ErrorResponse('Find more error details in the log file.')
```
Comment (krishna-acondy) [inline src/commands/run.js:83]: It'd be good if we could output the path to the log file here.

File: src/commands/run.js [hunk 2]
```diff
@@ -122,13 +132,18 @@ async function executeOnSas9(buildTarget, linesToExecute) {
...
-    repositoryName
-  )
+  const executionResult = await sasjs
+    .executeScriptSAS9(linesToExecute, serverName, repositoryName)
+    .catch(async (err) => {
+      let log = err.payload.log
+
+      await createOutputFile(log)
+
+      throw new ErrorResponse('Find more error details in the log file.')
```
Comment (krishna-acondy) [inline src/commands/run.js:145]: It'd be good if we could output the path to the log file here.

File: src/utils/displayResult.js [hunk 3]
```diff
@@ -2,25 +2,39 @@ import chalk from 'chalk'
...
-        console.log(
-          chalk.redBright(
-            failureMessage,
-            `${message}${details ? '\n' + details : ''}`
-          )
-        )
-      } catch (parseError) {
-        console.log(chalk.redBright('Unable to parse error\n', parseError))
-        console.log(chalk.redBright(failureMessage, err.body))
+      if (err.error) {
```
Comment (krishna-acondy) [inline src/utils/displayResult.js:8]: This is basically the same as what was said on line 6.

File: src/utils/displayResult.js [hunk 4]
```diff
@@ -2,25 +2,39 @@ import chalk from 'chalk'
...
+        body = err.error
       }
+
+      if (!body) {
+        try {
+          body = JSON.parse(err.error)
```
Comment (krishna-acondy) [inline src/utils/displayResult.js:14]: If `body` is falsy, doesn't that automatically mean that `err.error` is falsy since it's assigned to `body`?

File: src/utils/displayResult.js [hunk 5]
```diff
@@ -2,25 +2,39 @@ import chalk from 'chalk'
 
 export function displayResult(err, failureMessage, successMessage) {
```
Comment (krishna-acondy) [inline src/utils/displayResult.js:3]: It should be pretty straightforward to add unit tests for this function to test all the scenarios.

File: src/commands/run.js (hunk 2 above)
Comment (medjedovicm) [reply src/commands/run.js:145]: The path is printed when file is created. So in the terminal it will be above this print.

File: src/commands/run.js (hunk 1 above)
Comment (medjedovicm) [reply src/commands/run.js:83]: `createOutputFile()` will print the path

File: src/utils/displayResult.js (hunk 4 above)
Comment (medjedovicm) [reply src/utils/displayResult.js:14]: Good point, this whole function need revisiting

**Review by krishna-acondy — APPROVED** [review]

File: src/main.js [hunk 6]
```diff
@@ -138,43 +103,26 @@ export async function deployServices(commandLine) {
...
-            `${message}
-            ${details ? '\n' + details : ''}`
-          )
-        )
+        displayResult(err, 'An error has occurred when building services.')
       } else {
-        console.log(
-          chalk.redBright('An error has occurred when deploying services.', err)
-        )
+        displayResult(err, 'An error has occurred when deploying services.')
```
[the remark this answers is not in the document]
Comment (krishna-acondy) [reply src/main.js:112]: That would help, but it'll probably be part of a bigger piece of work around improving the logging.

File: src/main.js [hunk 7]
```diff
@@ -210,33 +158,25 @@ export async function compileBuildDeployServices(commandLine) {
...
-          chalk.redBright(
-            'An error has occurred when building services.',
-            `${message}${details ? '\n' + details : ''}`
-          )
-        )
-      } else {
-        console.log(
-          chalk.redBright('An error has occurred when building services.', err)
-        )
+        if (status === 409) {
```
Comment (krishna-acondy) [inline src/main.js:177]: Why do we have this extra check for `409` here?

**Review by saadjutt01 — APPROVED** [review]

**Review by saadjutt01 — APPROVED** [review]

**Review by krishna-acondy — APPROVED** [review]
