### PR TITLE
fix: add the support for .bat and .ps1 files

### LINKED ISSUE #1248: run build script without servicepack
I would like to be able to run a build script with `sasjs deploy` without servicepack

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1248

## Intent

* `sasjs deploy` should execute .bat and .ps1 files along with .sh files if provided in deployScripts array of deployConfig

## Implementation

* add a utility function to execute power shell scripts

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/deploy/internal/deployToSas9.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+ * Execute deployScript on `SAS9` server.
+ * @param {string} deployScriptName - name of deploy script.
+ * @param {Target} target - the target having deploy configuration.
+ * @param {string[]} linesToExecute - array of SAS code lines of deploy script to execute.
+ * @param {string} logFolder - optional path to log folder,
+ * log file name will be <deploy-script-name>.log
+ * @param {object} streamConfig - optional configuration object of StreamConfig
+ * for printing web app url on console.
+ */
+export async function deployToSas9(
```
Comment (allanbowe) [inline src/commands/deploy/internal/deployToSas9.ts:21]: Could this be renamed to `executeDeployScriptSas9`?

**Review by allanbowe — CHANGES_REQUESTED** [review]

**Review by allanbowe — APPROVED** [review]
