### PR TITLE
fix: display error message on not getting access tokens

### LINKED ISSUE #1136: sasjs auth incase of invalid authcode
HTTP request got 400 bad request response:
 
image

But cli is not handling this.
image

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Fixes #1136

## Intent

Should handle such case and display error message on console.

## Implementation

Added check on accesstoken and refreshtoken if not present show error message.

Updated cli response:
image

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

**Review by allanbowe — DISMISSED** [review]

File: src/commands/add/addCredential.ts [hunk 1]
```diff
@@ -162,7 +162,9 @@ export const getTokens = async (
     target
   ).catch((e) => {
     process.logger?.error(
-      `An error has occurred while validating your credentials: ${e}\nPlease check your Client ID ${
+      `An error has occurred while validating your credentials: `,
```
Comment (YuryShkoda) [inline src/commands/add/addCredential.ts:165]: you should concatenate these string because `process.logger.error` expect 1st argument to be a message

**Review by medjedovicm — DISMISSED** [review]

**Review by YuryShkoda — APPROVED** [review]

**Review by medjedovicm — APPROVED** [review]
