### PR TITLE
fix(web): apploc with spaces + default value for streamServiceName at root

### LINKED ISSUE #828: sasjs streamed apps with spaces in urls
When the `appLoc` contains spaces, we should pad them with `%20` to make the URL clickable

Also, a missing [`streamServiceName`](https://cli.sasjs.io/sasjsconfig.html#streamConfig_streamServiceName) attribute should not result in an `undefined' in the url (when `streamConfig` is defined in the sasjsconfig root)

image

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #828 

## Intent

If streamConfig is at root level, need to use default value for `streamServiceName: 'clickme'`.
If appLoc has spaces in it, deployed link on console/log must be pad with `%20`, to make the URL clickable

++ changing file extension for SAS9 to create SAS Program bug. 
++ Should convert `./abc.hash.js.map` to `./abc.hash.js-map.sas`

++ Issue for SAS9, unable to load properly base64 encoded for `ICO` in index.html Program.

## Implementation

Added new function to `utils/config`, `getStreamConfig` to always have prioritised config from root & target-specific.
Added `appLoc` to `getLaunchPageCode`, space gets converted to `%20`
Removed `updateFaviconHref`, as it's redundant now.
Updated `sasjsout.ts` to support `ICO` file type.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
image
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All CI checks are green.
- [x] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

### CODE REVIEW

**Review by krishna-acondy — APPROVED** [review]
Looks good to me. There seems to be a merge conflict with the package-lock.json from `main` though.

**Review by krishna-acondy — APPROVED** [review]

File: src/commands/build/internal/getLaunchPageCode.ts [hunk 1]
```diff
@@ -1,18 +1,18 @@
...
+const SAS9Code = (streamServiceName: string, appLoc: string) => `
 options notes;
 data _null_;
  format url $256.; 
  rc=METADATA_GETURI("Stored Process Web App",url);
  url=coalescec(url,"localhost/SASStoredProcess");
  putlog "NOTE: SASjs Streaming App Created! Check it out here:" ;
  putlog "NOTE- ";putlog "NOTE- ";putlog "NOTE- ";putlog "NOTE- ";
- putlog "NOTE- " url +(-1) "?_program=&appLoc/services/${streamServiceName}" ;
+ putlog "NOTE- " url +(-1) "?_program=${appLoc}/services/${streamServiceName}" ;
```
Comment (allanbowe) [inline src/commands/build/internal/getLaunchPageCode.ts:11]: This should remain as `&appLoc` so that the generated build.sas file can be modified by the end user by simply updating the `%let apploc=xxx;` at the start (otherwise it will get hard coded from the sasjsconfig attribute)

File: src/commands/build/internal/getLaunchPageCode.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ data _null_;
    else url="&systcpiphostname";
  end;
  else url="&systcpiphostname";
- url=cats(url,"/SASJobExecution?_FILE=&appLoc/services/");
+ url=cats(url,"/SASJobExecution?_FILE=${appLoc}/services/");
```
Comment (allanbowe) [inline src/commands/build/internal/getLaunchPageCode.ts:25]: same issue here (the appLoc needs to be resolved in SAS, so that it can be a parameter at the start of the build.sas program)

**Review by allanbowe — CHANGES_REQUESTED** [review]
Need to address the {appLoc} issue otherwise looks good

**Review by VladislavParhomchik — DISMISSED** [review]

File: src/commands/build/internal/getLaunchPageCode.ts (hunk 1 above)
Comment (saadjutt01) [reply src/commands/build/internal/getLaunchPageCode.ts]: fixed

File: src/commands/build/internal/getLaunchPageCode.ts (hunk 2 above)
Comment (saadjutt01) [reply src/commands/build/internal/getLaunchPageCode.ts]: fixed

**Review by VladislavParhomchik — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
