### PR TITLE
fix(docConfig): enableLineage + target precedence + data in docs header

### LINKED ISSUE #476: sasjs doc not excluding sasjs/core
To reproduce:

```
git clone git@github.com:KatjaGlassConsulting/SMILE-SmartSASMacros.git
cd SMILE-SmartSASMacros
npm i 
sasjs doc
```

The generated docs include the sasjs/core macros, even though `"displayMacroCore": false`.  Perhaps we should add a flag to `displayNodeModules` ?  Especially as more SAS Macro libraries are added as NPM dependencies.

### LINKED ISSUE #478: sasjs doc improvements
- Take metadata from package.json, eg project brief and the github repo
- have a switch-in docConfig for turning off the lineage
- rename `sasjs-logo.png` to just `logo.png` so the new logo just needs to replace the old one

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #478 
Closes #476 

## Intent

Add `enableLineage` to `docConfig` and have precedence at property level of `docConfig` ref. Target and root level

## Implementation

Added `enableLineage`
- `sasjs doc` will not generate dot files if `enableLineage = false`
Following extracted from project's package.json and passed to docs html
- PROJECT_NAME, PROJECT_BRIEF, PROJECT_REPO
- packageJson.name, packageJson.description, packageJson.homepage
- doxy template header.html updated
- tests added/updated
- verify functions moved to `src/utils/test.ts`

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

### CODE REVIEW

File: src/commands/docs/generateDocs.ts [hunk 1]
```diff
@@ -59,10 +65,27 @@ export async function generateDocs(targetName: string, outDirectory: string) {
...
+  let PROJECT_REPO = 'https://github.com/sasjs/cli'
+
+  const packageJsonContent = await readFile(
+    path.join(process.projectDir, 'package.json')
+  )
+  if (packageJsonContent) {
+    const packageJson = JSON.parse(packageJsonContent)
+    PROJECT_NAME = packageJson.name
+    PROJECT_BRIEF = packageJson.description
+    PROJECT_REPO = packageJson.homepage
```
Comment (allanbowe) [inline src/commands/docs/generateDocs.ts:79]: perhaps we need a default in case of missing or empty?  such as "Please add 'homepage' to your package.json"

File: src/doxy/Doxyfile [hunk 2]
```diff
@@ -24,9 +24,9 @@ INPUT                  = $(DOXY_CONTENT)../../README.md $(DOXY_INPUT)
 LAYOUT_FILE            = $(DOXY_CONTENT)DoxygenLayout.xml
 USE_MDFILE_AS_MAINPAGE = README.md
 MAX_INITIALIZER_LINES  = 0
-PROJECT_NAME           = SAS JS
-PROJECT_LOGO           = $(DOXY_CONTENT)sasjs-logo.png
-PROJECT_BRIEF          = "Command line interface for SASjs"
+PROJECT_NAME           = $(PROJECT_NAME)
+PROJECT_LOGO           = $(DOXY_CONTENT)logo.png
+PROJECT_BRIEF          = $(PROJECT_BRIEF) PROJECT_REPO=$(PROJECT_REPO)
```
Comment (allanbowe) [inline src/doxy/Doxyfile:29]: I'm worried about this part - what if there is no github repository?  I really like the way that you have implemented it (nice workaround) but we could be setting ourselves up for problems if the user simply doesn't use / want to use GIT.

Maybe it would be safer / more robust (cause less confusion) to just have the $PROJECT_BRIEF here?

File: src/doxy/new_header.html [hunk 3]
```diff
@@ -8,6 +8,7 @@
     <meta name="viewport" content="width=device-width, initial-scale=1" />
     <!--BEGIN PROJECT_NAME-->
     <title>$projectname: $title</title>
+    <meta name="description" content="$projectbrief" />
```
Comment (allanbowe) [inline src/doxy/new_header.html:11]: nice touch

File: src/doxy/new_header.html [hunk 4]
```diff
@@ -19,8 +20,19 @@
     <link href="$relpath^$stylesheet" rel="stylesheet" type="text/css" />
     <link rel="shortcut icon" href="$relpath^favicon.ico" type="image/x-icon" />
     $extrastylesheet
+    <script>
+      var [projectbrief, projectrepo] = '$projectbrief'.split(' PROJECT_REPO=')
```
Comment (allanbowe) [inline src/doxy/new_header.html:24]: see comment above.  This is a very nice workaround but I'm concerned about the complexity and the dependency we will be placing on the existence of a GIT repo

**Review by allanbowe — DISMISSED** [review]

File: src/commands/docs/generateDocs.ts (hunk 1 above)
Comment (saadjutt01) [reply src/commands/docs/generateDocs.ts:79]: https://github.com/sasjs/cli/pull/481/files/4377c1b724b411bf5ab9e831fc76ed821af5b35c#diff-e87d4a4f7828949b17fee99acd797cc46fa8cfd7d5ff48c451972cbb5c22a0feR68

Are we good with these as default values?

**Review by allanbowe — DISMISSED** [review]

**Review by allanbowe — APPROVED** [review]

File: src/utils/test.ts [hunk 5]
```diff
@@ -131,3 +137,131 @@ export const verifyFolder = async (folder: Folder, parentFolderName = '.') => {
...
+}
+
+export const updateDocConfig = async (
+  docConfig: DocConfig,
+  target: string | undefined = undefined
+) => {
+  const { buildSourceFolder } = getConstants()
+  const configPath = path.join(buildSourceFolder, 'sasjs', 'sasjsconfig.json')
+  const config = await getConfiguration(configPath)
+  if (target) {
```
Comment (krishna-acondy) [inline src/utils/test.ts:176]: Why is `target` a string, and why do we have this check?

Comment (saadjutt01) [reply src/utils/test.ts]: Previously, this function `updateDocConfig` is used to either update docConfig at root level or Target, for tests to check precedence.

Now this function is renamed to `updateConfig` as there's `updateTarget` as well, new commit is present.

**Review by allanbowe — DISMISSED** [review]

File: src/commands/docs/generateDocs.ts [hunk 6]
```diff
@@ -59,10 +65,27 @@ export async function generateDocs(targetName: string, outDirectory: string) {
...
 
+  let PROJECT_NAME = `Please update the 'name' property in the package.json file`
+  let PROJECT_BRIEF = `Please update the 'description' property in the package.json file`
+  let PROJECT_REPO = `Please update the 'homepage' property in the package.json file`
+
+  const packageJsonContent = await readFile(
+    path.join(process.projectDir, 'package.json')
+  )
+  if (packageJsonContent) {
+    const packageJson = JSON.parse(packageJsonContent)
```
Comment (YuryShkoda) [inline src/commands/docs/generateDocs.ts:76]: `JSON.parse` can throw an error. Please wrap it in `try-catch`.

**Review by YuryShkoda — CHANGES_REQUESTED** [review]

**Review by allanbowe — APPROVED** [review]
