### PR TITLE
fix: show proper runner error when runner is missing on sasjs deploy and sasjs request

### LINKED ISSUE #1318: sasjs request should display proper runner error when runner is missing
On server type sas9 when runner is missing, sasjs request should display a useful error indicating the missing of runner.
Currently, it shows only 
Screenshot from 2023-02-15 22-33-36

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #1318

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

### CODE REVIEW

File: src/commands/request/request.ts [hunk 1]
```diff
@@ -125,16 +125,8 @@ export async function runSasJob(
       result = true
     })
     .catch(async (err: any) => {
-      if (err && err.errorCode === 404) {
```
Comment (sabhas) [inline src/commands/request/request.ts:128]: this removed chunk of code was useless here. Because the `displayError` function is handling this scenario in the invoking function.

File: src/commands/deploy/internal/executeDeployScriptSas9.ts [hunk 2]
```diff
@@ -36,10 +36,7 @@ export async function executeDeployScriptSas9(
       authConfigSas9: { userName, password }
     })
     .catch((err) => {
-      process.logger?.log(formatErrorString(err))
```
Comment (sabhas) [inline src/commands/deploy/internal/executeDeployScriptSas9.ts:39]: Error thrown from sasjs adapter already contains the proper message for missing of sasjs runner. Therefore, its enough to print formatted error string. Also this statement would have never been executed because errorCode thrown from adapter  is 500 in case of missing of sasjs runner.

**Review by YuryShkoda — APPROVED** [review]
