### PR TITLE
fix(paths): fixed file paths for project assets

### LINKED ISSUE #429: sasjs deployScripts not running from correct directory
to reproduce:  

```
git clone git@github.com:sasjs/fileuploader.git
cd fileuploader
```

now in the sasjsconfig.json, set `"deployServicePack": false,`

Finally, run `sasjs cbd`

The error:

image

>  ERROR  Error: bash: /home/zah/git/fileuploader/sasjs/sasjs/build/copyscript.sh: No such file or directory      

The problem is the root - the default root for **all** `sasjs` commands should be the parent of the sasjs directory.  Here the default is expecting to be _inside_ the sasjs directory.

Expected - `sasjs cbd` works in the fileuploader repo (anywhere in the project, including the root) when `deployServicePack` is false.

### PR DESCRIPTION
**Pull request by YuryShkoda**
## Issue

closes #429 

## Intent

Standatize file paths of project assets.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

### CODE REVIEW

**Review by saadjutt01 — APPROVED** [review]

File: src/cli.ts [hunk 1]
```diff
@@ -39,23 +41,44 @@ export async function cli(args: string[]) {
...
     case 'deploy':
+      break
     case 'db':
+      break
     case 'compilebuild':
+      break
     case 'compilebuilddeploy':
+      break
     case 'web':
+      break
```
Comment (saadjutt01) [inline src/cli.ts:61]: We are using `process.projectDir` for deploy & web commands.

**Review by allanbowe — APPROVED** [review]
