### PR TITLE
fix: sasjs job execute issue for git-bash windows

### LINKED ISSUE #221: sasjs job execute issue
for some reason the `sasjs job execute` command is adding a _local_ filepath to the provided path.

SAS jobs _always_ execute on the server, so wouldn't expect this.

Also, the message says it has been submitted but that can't be correct as in fact it wasn't found:

image

### PR DESCRIPTION
**Pull request by saadjutt01**
## Issue

Closes #221 

## Intent

Bash breaks Windows tools by replacing forward slash with a directory path
POSIX path conversion: http://www.mingw.org/wiki/Posix_path_conversion

## Implementation

Written regex to replace if /git/ path is pre appended in args in cli.js file

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] All unit tests are passing (`npm test`).
- [x] All CI checks are green.

### CODE REVIEW

File: src/cli.js [hunk 1]
```diff
@@ -25,7 +25,8 @@ import { exit } from 'process'
 function parseCommand(rawArgs) {
   checkNodeVersion()
 
-  const args = rawArgs.slice(2)
+  // should update paths converted by POSIX in case of process.env.MSYSTEM is present
+  const args = rawArgs.slice(2).map((arg) => arg.replace(/(.*)\/Git\//i, '/'))
```
Comment (allanbowe) [inline src/cli.js:29]: My concerns here are:
1. What if the current folder does not end with "Git"
2. What if the SAS Drive folder contains the word "Git"

Can we somehow extract that renegade local directory, and use it in the regex?

**Review by allanbowe — APPROVED** [review]
